### ISSUE TITLE
generate BUILD dependency file

### ISSUE THREAD

**Issue by nosize** [thomasdesr/go-shorten#5]
Hi, how you generate BUILD dependency file in the vendor directory?

**Comment by thomasdesr** [comment]
I used gazel: https://github.com/mikedanese/gazel :D

Gazel seems to work well except for if a library is vendoring packages. PR #4 tracks most of the work I went through to get it working with this package

**Comment by nosize** [comment]
Thanks for the answer. I have found https://github.com/bazelbuild/rules_go/tree/master/go/tools/gazelle like too does the job.
